### ISSUE TITLE
Limit drag, resize, etc to a parent

### ISSUE THREAD

**Issue by sura2k** [nichollascarter/subjx#1]
Is it possible to restrict resize, rotate and move to a container?

**Comment by nichollascarter** [comment]
@sura2k , not possible yet, but I think it's not hard to implement. Maybe, it is will be done with the next update.

**Comment by shakoorattari** [comment]
Thanks @nichollascarter, Hopefully it will be optional.

**Comment by nichollascarter** [comment]
#30
