### ISSUE TITLE
event handling

### ISSUE THREAD

**Issue by Minimalpris** [nichollascarter/subjx#11]
Hi,

Great project :-)
It´s not possible to prevent the event on "onDrop" from fire other event.

Please see this exsample where it fires a click event on the container after onDrop.
(see console log)
  
http://jsfiddle.net/z6skbf7r/1/

Also the "**top center**" and "**bottom center**" handles do not work and the "**middle right**" and "**middle left**" do the same as "top right" and "top left"
( this is also a problem in your demo, testet in Chrome on windows)

btw.... your demo do not work in microsofe Egde, because it do not support:  "...methods" in the json config

Keep up the good work :-)

**Comment by nichollascarter** [comment]
@Minimalpris, hi :) 
Thanks for the response and interest. 
I will look your issue accurately and respond you in the few days.

**Comment by nichollascarter** [comment]
@Minimalpris,
About **preventing** - you can do it so:
1. Add click event listener to controls, where you activate the `drag` method:
`subjx('.draggable').drag(options).forEach(item => {
        subjx(item.controls).on('click', e => {
        	e.preventDefault();
         	e.stopImmediatePropagation();
        });
    });`
2. Check which element fires container onclick event and compare them:
`subjx('#container').on('click', e => {
    if (e.target !== e.currentTarget) return;...`

Check the [demo](http://jsfiddle.net/nichollascarter/oja3xpvk/).

About **handles**:
Yes, you are right, **tc** and **bc** handles do not work, but this is not a problem, this depends of **proportions** option. 
Before I resolve it, I need to decide handles roles with `proportions `option activated.

**P.S.**
This library production code transpiling to ES5 version, but I am supporter of modern JS versions and prefer to use it with modern browsers. 
Maybe I will redo the demo for resolving compatibility problems.
