### ISSUE TITLE
Contact

### ISSUE THREAD

**Issue by engenic** [nichollascarter/subjx#12]
Hello Karen,

I apologize for creating an Issue like this, but I could not find your contact details anywhere. 

Im interested in having some features built into the project.   I dont have the time to do it myself.  Are you interested in contract work to develop this project further?   Essentially, I would like to use this library to place objects on a map, and then save it so that it can be edited later.    An example would be to place tool images in a fire truck so that new firefighters can find the equipment.

eg: https://thumbs.dreamstime.com/b/inside-fire-engine-fire-truck-side-view-equipment-packed-neatly-58081935.jpg

There would be a tool box with objects and line drawing like you have which would be placed down.

vbaker@engenic.com   SUBJECT:  "SUBJX"

Cheers ~ ...Vern

**Comment by nichollascarter** [comment]
@engenic, hello! You can contact me by email nichollascarter@gmail.com
