### ISSUE TITLE
When the container is scaled, it cannot rotate properly

### ISSUE THREAD

**Issue by zefengguo** [nichollascarter/subjx#16]
eg:
```
<div class="container"  style="width: 500px; height: 500px; position: relative;transform-origin: center center; transform: scale(0.5); ">
</div>
```

Will you support this feature in the next release?
 Looking forward to your reply .

**Comment by nichollascarter** [comment]
Hi, thanks for the issue.
Looks like a bug, I will try to fix it and reply you as soon as possible.

**Comment by zefengguo** [comment]
OK.

**Comment by nichollascarter** [comment]
Please, try latest version and let me know if you still have the issue

**Comment by zefengguo** [comment]
I tried it, It's perfect, thanks.
