### ISSUE TITLE
Save/Load state?

### ISSUE THREAD

**Issue by d8ahazard** [nichollascarter/subjx#17]
Hi there! Awesome project!

I was wondering...how, exactly, would I save and load scale/rotation/position of items once they've been positioned in the browser?

**Comment by nichollascarter** [comment]
Hi, @d8ahazard! Thanks for question.

How you want to save your items? 
Or you want to save scale/rotation/position values only?

Can you describe purpose you follow?

**Comment by d8ahazard** [comment]
[image: image.png]

The resizable div will show the "layout" of a series of nanoleaf LED panels
in relation to a TV screen or monitor.

Once the user drops/scales/rotates the div, I want to save all coordinate
positions to a JSON array and store it with other info on the light panels.

When the page is re-loaded, I would then need to deserialize stored JSON
and re-draw where the user left it.

**Comment by d8ahazard** [comment]
![image](https://user-images.githubusercontent.com/1633844/73072565-efe64800-3e7a-11ea-95fc-0108bc7adf8e.png)

**Comment by d8ahazard** [comment]
Moved to:

![image](https://user-images.githubusercontent.com/1633844/73072610-07bdcc00-3e7b-11ea-9518-6dfd3d800c0c.png)

**Comment by nichollascarter** [comment]
Okay, I'll try to provide you simple demo which might to help you.

**Comment by d8ahazard** [comment]
To make this a little more complicated...or easier...or something...

I should *also* make the TV able to be moved and dragged, so that when I'm
doing my computations for the light data, I can reference both objects in
cartesian space to determine what colors to send to what panel and when...

Not sure if it makes a ton of difference, but ultimately, this UI will be
accessed via mobile and desktop, so the most important thing is being able
to reference the position and scale of the screen and panel in relation to
one another.

Sorry to make it more complicated...but I'd rather ask all the right
questions now. :D

>

**Comment by d8ahazard** [comment]
![image](https://user-images.githubusercontent.com/1633844/73111580-6497a180-3ed0-11ea-82d0-055b7c898346.png)

**Comment by engenic** [comment]
Ideally, all the information about objects on a screen should be stored in a database.  AJAX could be used to gather and send that information on each object move.   This would then allow the object editor to reside on a mobile phone or web app.   

If there could also be a menu of objects to drag and drop also created by a provided AJAX call, that would be very powerful.    I have a feeling that many people would adopt this project if there was an end to end demo like that.   

I would be willing to contribute a few $$ to make that happen.   I would be willing to also help program that, but Im at least a couple months out before I have any time.

**Comment by nichollascarter** [comment]
@d8ahazard, please take a look to this [example](https://codesandbox.io/s/jovial-euclid-892ot).
There is just writing values into previously deserialized object in the example.

I hope we are a little closer to your goal.
Waiting for your comments.
