### ISSUE TITLE
Moving / "Dragging" an element with arrow keys?

### ISSUE THREAD

**Issue by mageide** [nichollascarter/subjx#18]
Hi there Karen! 

Just stumbled upon your awesome project and it looks very useful. I was wondering if there is a way to move / "drag" an element using the arrow keys? Sometimes it comes in handy tu nudge an element a few pixels with the arrows instead of clicking and dragging. :-)

**Comment by nichollascarter** [comment]
Hi @mageide! Nice question!

This is not possible right now, but I totally agree with you, it is neccessary to provide API for dragging/rotating/resizing.

I'm planning to add this ability with next update.

I hope for your waiting. Thanks!

**Comment by mageide** [comment]
Great, I really appreciate that you put this on your roadmap. :-) Some times it makes more sense to either use the arrow keys or maybe an input slider or dialog box to do some adjustments and fine-tuning of position, rotation and scale. Looking forward to next release!

**Comment by nichollascarter** [comment]
@mageide, 

I have just released the new version with additional methods for dragging/resizing/rotating.
I provide to you tiny [demo](https://codesandbox.io/s/jovial-euclid-892ot) for dragging with using the arrow keys.

Looking forward for your reply :)

**Comment by mageide** [comment]
Excellent Karen!

I just tried the demo and moving the object around with the arrow key works perfect, exactly as I wanted it to be. Could you provide simple demos for scale and rotate as well, I guess others also might want to see a demo of those features too :-) 

Great work! And thanks a lot for the quick implementation!

**Comment by nichollascarter** [comment]
@mageide,

Great! I am glad I was able to help.

Thanks!
