### ISSUE TITLE
Restrict does only work left and top?

### ISSUE THREAD

**Issue by cvalues** [nichollascarter/subjx#20]
Hi,

restrict only works on the left side and the top?
Or what is wrong?

**Comment by nichollascarter** [comment]
Hi, @cvalues!

Restrict resizing/rotating is not supported yet.
It works for moving with single element.

If you have got some issues with moving an element, please, provide your example for
reproducing the problem.

Thanks.

**Comment by cvalues** [comment]
Hi, 
thanks for your answer.
The problems comes up with restirct and moving. I set this to the options: restrict: '#stack',
The restirction works on the left side and the top but not on bottom and right? There i can drag it over the border.

**Comment by nichollascarter** [comment]
@cvalues, 

I think I'll solve the problem in the few days.

Thanks.

**Comment by cvalues** [comment]
would be great, thx alot!

**Comment by locomot1f** [comment]
yes, i have also noticed this. 
the container box is only containing the top & left of the container box.

**Comment by milanhawkins** [comment]
Any idea whether restricting resizing is likely to be implemented?

**Comment by DoimoInterlogica** [comment]
This update would be quite useful.

**Comment by nichollascarter** [comment]
#30

**Comment by sraza295** [comment]
@milanhawkins 
Did you implemented to restrict the resizing an elemen?

**Comment by milanhawkins** [comment]
Looks like this is fixed in the latest version.

**Comment by sraza295** [comment]
@milanhawkins 
Please can you help me,
which method should I use for this?

I want to resize up to 200px of height.
After that, the height should be not resizable.
