### ISSUE TITLE
Texts support (in the future)?

### ISSUE THREAD

**Issue by AstroCorp** [nichollascarter/subjx#21]
Texts support (in the future)?

**Comment by nichollascarter** [comment]
It will be possible in the near future.

**Comment by Abdulmanan0315** [comment]
Text are perfectly supported at the moment But I am unable to increase or decrease the size of the text by dragging from All Handles.
Currently according to version **0.3.6**, I think by stetching the Right middle and Left Middle handles the letter spacing of the text is increased but not the size.

Looking for that feature especially as its an important feature.
Thanks for such a powerful plugin.

**Comment by nichollascarter** [comment]
@Abdulmanan0315, you are right, text resizing is not totally supported.
But you can use set `scalable` option to `true`. It might scale your text tag instead of resize.

Maybe it would be better to use foreignObject?

**Comment by numangrewal** [comment]
Yes foreignObject is good but actually i am converting the native svgs to video thus encoders doesn't support foreignObject at the moment (They mey support as SVG 2.0 gets integrated into browsers more and more).
So for that i have to go with all the natural tags of svg.

I ll try the scalable option and let you know.

**Comment by numangrewal** [comment]
WoW . THE scaling thing worked perfectly for text and all the tspans inside.
But i want to is there any way to use that scalable option only for specific elements like if i want to use them for text only but not for images etc.?

**Comment by nichollascarter** [comment]
@numangrewal, unfortunately i can't propose to you built-in desicion for detecting specific element right now.

Perhaps, you should try something like this: `subjx(element).drag({ scalable: element.tagName.toLowerCase() === 'text' })`.

**Comment by Abdulmanan0315** [comment]
@nichollascarter its giving **element** is not defined

**Comment by nichollascarter** [comment]
@Abdulmanan0315 
i meant something like it 
```javascript
const element = document.getElementById('my-draggable');
subjx(element).drag({ scalable: element.tagName.toLowerCase() === 'text' });
```

**Comment by Abdulmanan0315** [comment]
@nichollascarter Sorry my bad.
Nope, it doesn't work and that actually returns true and all the elements becomes scalable.
Is there any callback function something like **OnScale**  like all the other callbacks where i can check if i should allow scaling for current element or not?

**Comment by nichollascarter** [comment]
@Abdulmanan0315 

let summarize an issue: you need to 'scale' text tag or another specific element and 'resize' others?
i am not able to test right now, but you can use `onInit` method and check it by this way: 
```javascript
onInit() {
  this.options.scalable = this.el.tagName.toLowerCase() === 'text';
}
```

**Comment by Abdulmanan0315** [comment]
@Abdulmanan0315 
Thanks man that did the trick and its working perfectly fine.
