### ISSUE TITLE
Undo / Redo Feature

### ISSUE THREAD

**Issue by alextate4** [nichollascarter/subjx#23]
An undo and redo feature would also be a great addition! Thanks.

**Comment by nichollascarter** [comment]
Yes, this is important part of any mapping application, but it not related to the library logic.

Your logic can be imagined with next steps:

1. Use method such as `onMove` for saving new parameters in stack.
2. For undo you simply `pop` the last item in stack.
3. Apply it with API method `exeDrag`.

I did not test it, but it can be useful.

Thanks.
