### ISSUE TITLE
Get transform matrix on "resize" event.

### ISSUE THREAD

**Issue by inditheme** [nichollascarter/subjx#25]
Hi Nichollas,

Thanks for your great work. Its nice plugin. Just want to ask, is there any way to pull transform matrix on resize event?
I can get transform matrix via API for drag and rotate event, but unfortunately can't for resize.

Thanks for your advance,
Regards.

**Comment by nichollascarter** [comment]
Hi @inditheme,

Looks like my omission. 
I will add it with next release.

Thanks.

**Comment by inditheme** [comment]
Sorry, just posted question without looking first. 
Thanks for your reply.
