### ISSUE TITLE
Change layering of elements?

### ISSUE THREAD

**Issue by nathalieroemer** [nichollascarter/subjx#27]
Hi, is it possible to change the layering of the elements by clicking on them (or having a menu to select what is in the foreground, what in the background?). Thanks!

**Comment by nichollascarter** [comment]
Hi @nathalieroemer. It is not possible right now. I think this possibility can be implemented but with low priority.

**Comment by Abdulmanan0315** [comment]
@nathalieroemer You can use SVG.js library to move elements forward,backward,front,back easily with a single function like;

element.forward();
element.backward();
