### ISSUE TITLE
Really Great Plugin

### ISSUE THREAD

**Issue by Abdulmanan0315** [nichollascarter/subjx#29]
I was struggling with the dragging and resizing things, I am using gsap and then i found this plugin, Its a breeze;
Now my only request here is that Please maintain this plugin so that we can all make this better.
I can provide financial managers to you.

**Comment by nichollascarter** [comment]
hi @Abdulmanan0315,

I am planning to maintain project more actively. 
Perhaps, I will need financial contribution, but for this I need to spend more time to project.
Please follow the updates, create issues if you faced the problem while using the library.

Thanks!

**Comment by Abdulmanan0315** [comment]
Hi @nichollascarter,
Thanks for the reply. I am using the library and if i got any issue i ll just post it.
For Financial contribution i might help. I just need a little time to get things going.

Thanks for such a powerful tool.
