### ISSUE TITLE
windows scroll offset problem fixed

### ISSUE THREAD

**Issue by alperonur** [nichollascarter/subjx#3]
replace offset(node) with: 

    function offset(node) {
        var _offset = node.getBoundingClientRect();
        
        var _scrollLeft = 0;
        if(document.documentElement)
        	_scrollLeft = document.documentElement.scrollLeft;
        else if(document.body.parentNode)
        	_scrollLeft = document.body.parentNode.scrollLeft;
        
        var _scrollTop = 0;
        if(document.documentElement)
        	_scrollTop = document.documentElement.scrollTop;
        else if(document.body.parentNode)
        	_scrollTop = document.body.parentNode.scrollTop;

        return { bottom: _offset.bottom, height: _offset.height, left: _offset.left + _scrollLeft, right: _offset.right, top: _offset.top + _scrollTop, width: _offset.width, x: _offset.x, y: _offset.y };
    };

**Comment by nichollascarter** [comment]
This problem fixed with latest commit
