### ISSUE TITLE
ForeignObject Support

### ISSUE THREAD

**Issue by Abdulmanan0315** [nichollascarter/subjx#36]
As the title suggest Foreign object support should be made possible.
I have developed this piece of code to make elements inside foreign object movable By using a rect inside a **g** and then using the data from rect, apply that data on the foreign object elements. but its like in an ups and down state and buggy.

**HTML:**
```
<g x="100" y="100">
  <foreignObject x="100" y="100" width="200" height="200">
    <body xmlns="http://www.w3.org/1999/xhtml">
      <video xmlns="http://www.w3.org/1999/xhtml" src="myvideo.mp4" width="100%" height="100%"></video>
    </body>
  </foreignObject>
  <rect id="id" data-original-id="myid" type="video" class="drag-svg" x="100" y="100" width="200" height="200" fill="red" fill-opacity="0"></rect>
</g>
```

**JS:**

```
// Subjx - additional draggable,resizable and rotatable functionality
function makeDraggableSubjx(element, controls, event, type = false, width = false, height = false) {
    let elm, x, y, rotate, trnf, controls_transform;
    if (type) {
        elm = $(element).prev();
    } else {
        elm = $(element).prev();
    }

    switch (event) {
        case 'init':
            trnf = $(controls).attr('transform');
            x = $(controls).find('rect').attr('x');
            y = $(controls).find('rect').attr('y');

            elm.attr({x: x, y: y, transform: trnf});
            break;
        case 'move':
            trnf = $(controls).attr('transform');
            x = $(controls).find('rect').attr('x');
            y = $(controls).find('rect').attr('y');

            // Set x & y position
            elm.attr({x: x, y: y, transform: trnf});
            break;

        case 'resize':
            trnf = $(controls).attr('transform');
            x = $(controls).find('rect').attr('x');
            y = $(controls).find('rect').attr('y');

            elm.attr({x: x, y: y, transform: trnf, width: width, height: height});
            break;

        case 'rotate':
            trnf = $(controls).attr('transform');
            x = $(controls).find('rect').attr('x');
            y = $(controls).find('rect').attr('y');

            let controls_rotate = SVG(controls).transform('rotate');
            elm.attr({x: x, y: y, transform: trnf, angle: controls_rotate});
            break;

        case 'drop':
            trnf = $(controls).attr('transform');
            x = $(controls).find('rect').attr('x');
            y = $(controls).find('rect').attr('y');

            // Set x & y position
            elm.attr({x: x, y: y, transform: trnf});
            break;
    }

    elm, x, y, rotate, trnf, controls_transform = null;
}
```

**Registering the function inside move,edit,rotate etc.**

```
  onInit(el) {
      switch ($(el).attr("type")) {
          case 'video':
              makeDraggableSubjx(el, this.controls, 'init');
              break;
      }
  },
  onMove({clientX, clientY, dx, dy, transform}) {
      switch ($(this.el).attr("type")) {
          case 'video':
              makeDraggableSubjx(this.el, this.controls, 'move');
              break;
      }
  },
  onResize({clientX, clientY, dx, dy, width, height}) {
      switch ($(this.el).attr("type")) {
          case 'video':
              makeDraggableSubjx(this.el, this.controls, 'resize', false, width, height);
              break;
      }
  },
  onRotate({clientX, clientY, delta, transform}) {
      switch ($(this.el).attr("type")) {
          case 'video':
              makeDraggableSubjx(this.el, this.controls, 'rotate');
              break;
      }
  },
  onDrop({clientX, clientY}) {
      switch ($(this.el).attr("type")) {
          case 'video':
              makeDraggableSubjx(this.el, this.controls, 'drop');
              break;
      }
  },
```

Looking for better implementation.
Thanks for this beautiful plugin.

PLUS: using SVG.js plugin up there (for an aid to manuplate svg easily)

**Comment by nichollascarter** [comment]
hi @Abdulmanan0315 

I've implemented foreign objects support since 0.3.1 version.
If you're using lower version migration will be too painful. Please test it before updating version.

I will test your example with latest version and let you to know about the result.

Thanks.

**Comment by nichollascarter** [comment]
@Abdulmanan0315 , please check this [example ](https://codesandbox.io/s/foreign-object-example-5sk13).

Is this close to your expectations about foreign object support?

**Comment by Abdulmanan0315** [comment]
Thanks man for this support. Its working fine but there seems to be some bugs about that:
The width and height of the rect and the foreign object doesn't seems to fit in the svg-wrapper.
It fits only when we resize the object to left.

<img width="762" alt="Screenshot (5)" src="https://user-images.githubusercontent.com/20532497/110473034-e613b880-80ff-11eb-854c-179fc9ebe64f.png">

But isn't there any support for the foreignObject element directly? Like instead of creating a g and then creating inside of that foreignobject and a rect to aid?

**Comment by nichollascarter** [comment]
I've just tested on foreignObject element directly. It seems to work properly or I missed something.
Please approve(provide test sandbox) if it does not work as you wish.

![6VX0H2N5C3](https://user-images.githubusercontent.com/7247874/110536732-7b2ba700-812a-11eb-95e1-8e4bd1abb6b5.gif)

**Comment by Abdulmanan0315** [comment]
Its working man. Thanks for that gif image.

                              <g id=" + uuid + " data-original-id=" + id + " type="animated_object" x="100" y="100" class="drag-svg"> +
                                <foreignObject x="100" y="100" width="200" height="200"> +
                                    <body xmlns="http://www.w3.org/1999/xhtml"> +
                                        <video xmlns="http://www.w3.org/1999/xhtml" src="/Case study VP9.webm#t=0.1" width="100%" height="100%"></video> +
                                    </body> +
                                </foreignObject> +
                                <rect x="100" y="100" width="200" height="200" fill="red" fill-opacity="0"></rect> +
                            </g>;

Actually i was wrapping the foreignObject inside a g element and thats why it wasn't working.
Thanks man. !!!
