### ISSUE TITLE
TypeError: Argument not an object

### ISSUE THREAD

**Issue by ghost** [nichollascarter/subjx#41]
I'm new to this library and I'm getting this error: `Uncaught TypeError: Window.getComputedStyle: Argument 1 is not an object`. I didn't install it through npm though. I just imported it as a CDN by JSDelivr. Could this be the problem?

**Comment by nichollascarter** [comment]
hi @LukoFoks

Can you please provide the link which you used?

That was UMD build `dist/subjx.js`?

**Comment by LukoFoks** [comment]
I used the source links by JSDelivr

1. https://cdn.jsdelivr.net/npm/subjx@0.3.7/dist/js/subjx.js
2. https://cdn.jsdelivr.net/npm/subjx@0.3.7/dist/style/subjx.css

**Comment by nichollascarter** [comment]
I tried to use these links and it works without any errors.
You can check it [here](http://jsfiddle.net/nichollascarter/wzgbta54/2/).

Can you provide your sandbox?
Which browser do you use?

**Comment by rozbyn** [comment]
The same problem. It appears when target element appended directly on body. 
![Screenshot_234](https://user-images.githubusercontent.com/34918480/120471238-26a46a80-c3ad-11eb-86e5-9774a9b8df0f.png)
![Screenshot_235](https://user-images.githubusercontent.com/34918480/120471253-2ad08800-c3ad-11eb-871c-f56b23b4993b.png)
![Screenshot_236](https://user-images.githubusercontent.com/34918480/120471259-2c01b500-c3ad-11eb-8486-1a510f0269c0.png)

**Comment by qbadev** [comment]
It seems that parent object needs to be absolutely positioned and have width and height set.
