### ISSUE TITLE
Resize components

### ISSUE THREAD

**Issue by fahamidev** [nichollascarter/subjx#43]
Hi everyone.
How to resize all components inside the container when the container resize?

**Comment by nichollascarter** [comment]
Hi @fahamidev, 

What does `container` mean in context?
Do you need resize svg elements? 

Could you please provide minimal example?

**Comment by fahamidev** [comment]
By container I mean the element with `id="stack"` in below code.
I need all element's size changed, when stack element resized;
for example if stack with and height changed dynamically all images relatively appropriate changed the size 

for example if stack width and height changed dynamically all images size relatively appropriate changed.

For draggable class `proportions` property is `true`.

Code example: 
```
 <div id="stack" style="width: 500px; height: 500px">
            <div id="container" style="width: 100%; height: 100%">
                <img class="draggable" src="example.png" alt="" style="width: 100px; height: 100px">
                <img class="draggable" src="example.png" alt="" style="width: 100px; height: 100px">
                <img class="draggable" src="example.png" alt="" style="width: 100px; height: 100px">
                <img class="draggable" src="example.png" alt="" style="width: 100px; height: 100px">
            </div>
        </div>
```

**Comment by nichollascarter** [comment]
@fahamidev ,

Resizing for nested elements supported for svgs only.

It is need to be implemented, but I think this will not happen soon.

I will notify about any updates.

**Comment by fahamidev** [comment]
@nichollascarter Thank you very much for your very good library.
I am waiting for your notify. 🌹🙏
