### ISSUE TITLE
Multiple sjx-wrapper's

### ISSUE THREAD

**Issue by qbadev** [nichollascarter/subjx#46]
Chrome 91.0.4650.0 x64
subjx 0.3.9

After init object's transformations and using it a bit, object gets more than one `.sjx-wrapper`, and it gets messy on the screen. It also becomes difficult to use transformation then.

![ezgif-6-fec708b3f7c0](https://user-images.githubusercontent.com/293101/129065991-81a110e8-069c-41da-a361-b87503cd49ef.gif)

**Comment by nichollascarter** [comment]
hi @qbadev,

can you please create small reproducible example and provide a link?

**Comment by qbadev** [comment]
It was a mistake. I was instantiating `drag` several times without checking if object is already transformable. Sorry for a disturb
