### ISSUE TITLE
Rotating to 90deg disables rotating and resizing

### ISSUE THREAD

**Issue by qbadev** [nichollascarter/subjx#47]
It is a Basic Example from repo github page. I removed few elements and refectored JS script.
When starting from 0 and rotating to 90, -90, 270 or -270 degrees (releasing mouse button), it becomes impossible to rotate or resize object no more. It happens when angle snap is set positive or default (10). When set to 0, it is tough to set exact 90 angle, so the issue does not happen then.

Chrome 91 x64, Firefox latest, Ubuntu 20.04 x64

http://jsfiddle.net/qr9pc23y/1/

**Update**

Also if you start with object rotated (translated) by 90deg, resize and rotate is not working.

**Comment by HuzarO** [comment]
Hey, have you fixed that issue?

**Comment by HuzarO** [comment]
I've figured it out, the problem was with `matrixInvert` function logic. I've replaced that function with builtin function from MathJS library called `inv`.

**Comment by nichollascarter** [comment]
@HuzarO I'll take a look today. If it can be fixed quickly I'll try to fix it asap.

**Comment by Alaa-Elghamry** [comment]
> @HuzarO I'll take a look today. If it can be fixed quickly I'll try to fix it asap.

Hi, have you figured out a way to fix it yet? 
I have been doing a small project with your library and it works amazing

**Comment by qbadev** [comment]
I confirm, it works now
http://jsfiddle.net/v2u50ofb/3/
