### ISSUE TITLE
Live elements?

### ISSUE THREAD

**Issue by godoyrw** [nichollascarter/subjx#5]
It's possible enable/disable live elements?
Or maybe doubleclick in image to activate/deactivate?

I am creating an image editor, texts, svg ...
The elements are created on demand, hence my question.

Your plugin is fantastic, congratulations and thanks for sharing!

**Comment by nichollascarter** [comment]
Thank you for asking and sorry for a long responce.
If I correctly understand, you want to create an element, and after activate/deactivate element's transformation. You can use methods with existed elements only, but when it must be actived depends of your application.
But, your question gave me some idea and in a few days I'll try to implement simple activating/deactivating.

**Comment by godoyrw** [comment]
Do not apologize for the long responce.
Yes on elements dynamically created by javascript, enable / disable, this would require it!

Example: javascrip adds an element of type img, as it applies after upload!

**Comment by nichollascarter** [comment]
@godoyrw, please check [demo](http://jsfiddle.net/nichollascarter/qgwzch0v/). There is an example for dynamically created elements with double click activating/deactivating. 
Hope it helps you.

**Comment by godoyrw** [comment]
Perfect, that's right ... Thank you so much for your time and effort to help me!
