### ISSUE TITLE
rotationPoint option

### ISSUE THREAD

**Issue by frenchcdsl44** [nichollascarter/subjx#56]
Hi

Sorry to bother you again. 

You did not specify on the readme the rotationPoint option.
I tried to put a boolean and it works fine I can drag the rotation center.

I also tried 
` rotationPoint: [200, 200], `
but it does not seem to change the position of this point.

Is there anyway to move this point in the init function ? Maybe by adding parameters to the function resetCenterPoint?

Thanks I am already greatly impressed by the possibilities enabled by subjx.

**Comment by nichollascarter** [comment]
hi @frenchcdsl44 

Yeah, you are right, i did not specify `rotationPoint` option, because it is an experimental option.

> rotationPoint: [200, 200],

If you want set initial position you need to use staging version.
Please take a look to this [example](http://jsfiddle.net/5xa73t4b/).

I will add it to stable version when it it will be tested well.

Please let me know if you will have any troubles with lib usage.

**Comment by frenchcdsl44** [comment]
Hi

I think defining the rotation point in a callback method could be useful.
I made a quick patch #57 that I tested in my very limited use case. 
I am so far more of a jquery user than a real es6 developer, but I am willing to learn so don't hesitate to tell me if I can help.

Thanks

**Comment by nichollascarter** [comment]
Thanks for PR

Probably it is better to add new method called like `setCenterPoint`, because `reset` could be confusing.

**Comment by nichollascarter** [comment]
@frenchcdsl44 ,

i prepared PR ^ with your proposed functionality, please take a look and let me know if you will have any thoughts

**Comment by frenchcdsl44** [comment]
It looks excellent. I have my kids this week, but I try to test this as soon as possible

Thank you Santa Clauscarter

**Comment by frenchcdsl44** [comment]
Hi @nichollascarter 

Sorry for the late feedback. 

This is truly amazing.

I tried absolute positioning
	this.setCenterPoint({x:10, y:20},true);
I tried relative positioning
	this.setCenterPoint({dx:10, dy:20},false);
I tried it in inInit and onDrop.

It work very well.

Congratulations and 2022 thanks.

I'll try to make my svg puppet now and post you a link when done
