### ISSUE TITLE
resetCenterPoint(); inside onDrop event does not work on 0.3.9

### ISSUE THREAD

**Issue by frenchcdsl44** [nichollascarter/subjx#58]
Hi

I was preparing a new PR for the setCenterPoint(x,y) method of #56 but while basing the code on the resetCenterPoint(); I noticed it acts strangely.

You can see the demo here : 
https://codesandbox.io/s/svg-drag-pan-zoom-forked-dfjer

I changed subjx to version 0.3.9 (1.0.0 gives an error) and changed the option  :
` rotationPoint: true,`
and added in the callback :
```
  onDrop(e, el) {
    console.log("is dropped");
    this.resetCenterPoint();
  },
```
When the svg is dropped the control center seems to be shifted

I am still discovering the complexity of transformation matrix, but not enough to understand the issue.

Thanks

**Comment by nichollascarter** [comment]
Hi

Yes, i see the problem. Let me check it.

**Comment by nichollascarter** [comment]
@frenchcdsl44, please, re-check your issue with latest release.

**Comment by frenchcdsl44** [comment]
@nichollascarter 

Thank you. This is the main good news of my week.
