### ISSUE TITLE
Final size and rotation

### ISSUE THREAD

**Issue by arikanorh** [nichollascarter/subjx#7]
While i rotate or resize the item, the events gives the delta changes but not final values. So when i rotate element it gives, 0 10 20 30 until i release mouse button then starts again 0. 10 20

In this way, there is no way i can track what is the final rotation or sizes of the element. 

For size, i'm reading the width/height property of DOM element. This kinda works

For rotation, I had to to very bad things 

![image](https://user-images.githubusercontent.com/17791032/59329625-fbc03800-8cf7-11e9-88b1-7b62c13c7a77.png)

**Comment by nichollascarter** [comment]
You are right, you can get only the deltas. I do not see the point to calculate final values presently. 
If you look the code, final rotation degree value do not calculate as separate value, but only final matrix by matrix multiplication.

**Comment by arikanorh** [comment]
Yeah. For workaround, i parse the matrix and calculate the final rotation.

I'm building and design editor and user will save the items to the database. So I need the rotation value to save the database.
