### ISSUE TITLE
Drag and Drop dynamically is not working

### ISSUE THREAD

**Issue by sraza295** [nichollascarter/subjx#78]
Hello, 
I am using official basic example of subjx.
I am trying to drag and drop dynamically but its not working.
I have commented the line number 22 in HTML file. due to this its not working.
I have commented because it was automatically placed in canvas, but i want only when we do drag and drop.

Please check this jsfiddle :- https://jsfiddle.net/sraza295/ahberk52/43/ 

@nichollascarter @semantic-release-bot @sysmaya

**Comment by nichollascarter** [comment]
@sraza295 it happened because you still try to initialize new draggable elements with non existent selector:
```js
const Draggables = [subjx('.draggable').drag(options)];
```

replace with:
```js
const Draggables = [];
```

**Comment by sraza295** [comment]
@nichollascarter 
Thanks issue has been resolved.
