### ISSUE TITLE
Option to keep aspect ratio when resizing

### ISSUE THREAD

**Issue by adoo** [nichollascarter/subjx#8]
It would be a great feature! :)

**Comment by adoo** [comment]
I believe that this fork does this:
https://github.com/ivanandonov/subjx/commits/master

**Comment by adoo** [comment]
I retract my previous comment, invanandonov-fork did not resize properly. 
There is a [pull request](https://github.com/nichollascarter/subjx/pull/10) If you would like my changes - it is very simple :)

**Comment by nichollascarter** [comment]
@adoo, great, thanks! I need to check it with svg elements too. 
Sorry for the waiting.

**Comment by nichollascarter** [comment]
@adoo, I used your code with latest commit. 
I did not merge a pull request because of local changes in the project. 
Thanks!

**Comment by adoo** [comment]
I'm going to close this then :)

**Comment by ivanandonov** [comment]
adoo yes it was buggy at the beginning but i fixed it and just added a method to change the angle of the object
